services:
  web:
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443" # for SSL
    environment:
      - ALLOW_OVERRIDE=true
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - "./database/la_couture_de_cp.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
    ports:
      - "3306:3306"